[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "d87fbf7a3004aff5f83bf00763cb7215a2dbd4b9"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "ce268d75ac1e421a2ec41c60a6c47bf195cf2e2558a2dc830fd4708f8789209f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "f7241ed6bee6f3e5b44707d68893369d1b5721c8"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "99331d81818b6754f9c48982f4758f5b8fd88b369cd6126a814dece7a0b58bae"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "fb4d1765c160700060ace5e1aea47e07431fb22f"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "bb1903db96285c6453ac80440e4a2aeb5f431cfc84baa396d158028a283461f7"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "6ee27d94bc7d06d34421b8422875db04012c16bd"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "d2b44df3f1e7968b1f5c45c284c0f3d7e58633b6f746c9574cce3a43258649e4"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "a9522e4521714b80cd0bf3423d01bb74ca0b83f9"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "02f6d59accebe7cd61106893925d3acc766d896bc48b0c21dc8c61fefd1e1063"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "700c1a925be2508b8eba6500cfe56be9fea0f0cc"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "e092852fe2dbb8fd0848f030cf9a3f8b5244472f4d7ccfa50ba8fd43941799e0"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "90970d78810685a5671e288b4d515ccb5899663d"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "7dc4cfe3d605c936f1097518043f7b7f90e6f46892a0a7ad1db64544a7200cfb"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.x86_64-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "acf0bae4500cec8a8e346bdd2e24af77ae996b5f"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "07a4b21fa37c0d35cc9afd66dbcdc533864120dfc2f55d5136486c73995a0c87"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "8d1945727d29c6f287d2bb8f2fdd9b96e77f4e56"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "9f98deecaef1eb34a461ef41e068786d6cd1a729998f5727bf0d202581a43fc7"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.arm-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "28a797559aa3b114e381ae032fa13c0672521fd1"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "b4601b1fab56df7eb30db2b3d360465b03378579a0b9f04900f3354ba09cbd24"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "44aca495bfbef56adaf6d7b6d7ec3504da9ac102"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "7e01b4c4e584716591ded1467fe8e0e034cb48fc5bcad6a75a81ccc4c7eadfdc"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.arm-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "609b49736c3e90d3fd5ff7d705db3503a6e476ae"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "5246a8e19ea3daf1173ffc60c5cb6a53255e31144a813cab39def80892cb21c9"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "d4cb7dc0a6479e32e9f15e1547cbec63adff658a"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "0dae875ffafce57c29a0d547d108d9c7f85a22f6811075484470613c16a4af80"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+6/Fontconfig.v2.13.1.i686-w64-mingw32.tar.gz"
